project:
  type: book

book:
  title: "Numerics 0 WS23/24 Solutions"
  author: "Igor Dimitrov"
  date: "10/30/2023"
  chapters:
    - index.qmd
  downloads: pdf

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt